### ISSUE TITLE
Error doing job: Future exception was never retrieved

### ISSUE THREAD

**Issue by thibmaek** [custom-components/sickchill#3]
Started to install this using the following setup but does not work & produces this error output:

```console
Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sickrage/__init__.py", line 79, in sensor_update
    result = generic_command(host, api, 'shows.stats')
  File "/config/custom_components/sickrage/__init__.py", line 100, in generic_command
    result = requests.get(fetchurl, timeout=TIMEOUT, verify=False).json()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/site-packages/simplejson/decoder.py", line 373, in decode
    raise JSONDecodeError("Extra data", s, end, len(s))
simplejson.errors.JSONDecodeError: Extra data: line 1 column 5 - line 2 column 1 (char 4 - 17)
```

__init__.py & services.yaml are in the correct location and configuration.yaml contains:

```yaml
sickrage:
  host: "subdomain.externalhost.com/api"
  api_key: !secret sickrage_api_key
```

Visiting the host url (`subdomain.externalhost.com/api/key/cmd?=shows.stats`) locally works perfectly and shows the JSON output.

**Comment by thibmaek** [comment]
After this I got the following error:

```console
Error during setup of component sickrage
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/setup.py", line 148, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sickrage/__init__.py", line 94, in setup
    sensor_update(None)
  File "/config/custom_components/sickrage/__init__.py", line 79, in sensor_update
    result = generic_command(host, api, 'shows.stats')
  File "/config/custom_components/sickrage/__init__.py", line 100, in generic_command
    result = requests.get(fetchurl, timeout=TIMEOUT, verify=False).json()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/site-packages/simplejson/decoder.py", line 373, in decode
    raise JSONDecodeError("Extra data", s, end, len(s))
simplejson.errors.JSONDecodeError: Extra data: line 1 column 5 - line 2 column 1 (char 4 - 17)
```

**Comment by swetoast** [comment]
gonna look into it any additional information that we might take part of like if you performed any action etc when you got the error message?

**Comment by thibmaek** [comment]
Nope this is just when adding the component and doing a restart (of the app, not the system).

**Comment by swetoast** [comment]
ok will mess around with it and try and locate the bug

**Comment by ludeeus** [comment]
@thibmaek since you are using a domain name and no port, I assume you have SSL?
when you do not have shema in your string it assumes `http` and not `https`
If my assumption is correct change your config to this:
```yaml
sickrage:
  host: "https://subdomain.externalhost.com/api"
  api_key: !secret sickrage_api_key
```

**Comment by thibmaek** [comment]
@ludeeus this was already the case ;)

**Comment by ludeeus** [comment]
I think we need some more debug logs (not currently in the file for good reasons) to get any further here..
If you are on Discord, send me a PM `Ludeeus#4212`

**Comment by thibmaek** [comment]
The way I configured custom-components is here: https://github.com/thibmaek/homeassistant-conf

custom-updater seems to also produce an issue (UI notice that it couldn't be set up).

**Comment by ludeeus** [comment]
There is nothing wrong with the location of it, if there was you would see a `could not ind component *`
