### ISSUE TITLE
Won't start?

### ISSUE THREAD

**Issue by tortfeaser** [custom-components/sickchill#7]
Hi mate, thanks for this. 

Any ideas why I get this when restarting?

```Tue Jul 23 2019 14:38:41 GMT+1000 (Australian Eastern Standard Time)
Error during setup of component sickchill
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 156, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sickchill/__init__.py", line 94, in setup
    sensor_update(None)
  File "/config/custom_components/sickchill/__init__.py", line 79, in sensor_update
    result = generic_command(host, api, 'shows.stats')
  File "/config/custom_components/sickchill/__init__.py", line 100, in generic_command
    result = requests.get(fetchurl, timeout=TIMEOUT, verify=False).json()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
```

**Comment by swetoast** [comment]
Too old codebase, to little time to update
